
/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif



#include "STM32F103x8.h"
#include "stm32f103x8_GPIO_driver.h"

void delay(uint32_t milliseconds) {
    // Assuming a 1ms delay for each iteration
    volatile uint32_t count = 0;
    while (count < (milliseconds * 1000)) {
        count++;
    }
}

int main(void) {

    // Initialize clock configuration
	RCC_GPIOA_clock_enable();
	RCC_GPIOB_clock_enable();

	// pins configuration using MCAL_GPIO_init():
	// pins A1 and A13 as floating inputs
	// pins B1 and B13 as push-pull output

	GPIO_Config_TypeDef pin_Config;

	pin_Config.GPIO_Mode = GPIO_MODE_FLOATING;
	pin_Config.GPIO_pinNumber = GPIO_PIN1_MASK;
	MCAL_GPIO_Init(GPIOA, &pin_Config);

	pin_Config.GPIO_Mode = GPIO_MODE_OUTPUT_PP;
	pin_Config.GPIO_pinNumber = GPIO_PIN1_MASK;
	pin_Config.GPIO_Speed = GPIO_Speed_10;
	MCAL_GPIO_Init(GPIOB, &pin_Config);

	pin_Config.GPIO_Mode = GPIO_MODE_FLOATING;
	pin_Config.GPIO_pinNumber = GPIO_PIN13_MASK;
	MCAL_GPIO_Init(GPIOA, &pin_Config);

	pin_Config.GPIO_Mode = GPIO_MODE_OUTPUT_PP;
	pin_Config.GPIO_pinNumber = GPIO_PIN13_MASK;
	pin_Config.GPIO_Speed = GPIO_Speed_10;
	MCAL_GPIO_Init(GPIOB, &pin_Config);

    while (1){
    	if((MCAL_GPIO_ReadPin(GPIOA, GPIO_PIN1_MASK) == 0)){    // BUTTON PRESS, PUR
    		MCAL_GPIO_TogglePin(GPIOB, GPIO_PIN1_MASK);
    		while(MCAL_GPIO_ReadPin(GPIOA, GPIO_PIN1_MASK) == 0);
    	}
    	if(MCAL_GPIO_ReadPin(GPIOA, GPIO_PIN13_MASK) == 1){     // BUTTON PRESS, PDR
    		MCAL_GPIO_TogglePin(GPIOB, GPIO_PIN13_MASK);
    	}
    	delay(100);
    }
}



